=encoding utf8

=head1 NAME

Hello worldスクリプト

=head1 DESCRIPTION

Hello worldを出力するスクリプト。

=head1 METHODS

=begin html

<table>
  <tr>
    <td>a</td>
    <td>b</td>
  </tr>
</table>

=end html

=begin markdown

# テスト

=end

=begin markdown

= テスト

=end


=head2 say

=head3 DESCRIPTION

Hello worldを出力する

=head3 PARAMETERS

=over 1

=item *

input  ユーザー名

=back
